  0%|          | 0/250 [00:00<?, ?it/s]  0%|          | 1/250 [00:02<10:06,  2.44s/it]  1%|          | 2/250 [00:06<13:48,  3.34s/it]  1%|          | 3/250 [00:10<15:34,  3.79s/it]  2%|▏         | 4/250 [00:16<18:49,  4.59s/it]  2%|▏         | 5/250 [00:20<18:23,  4.50s/it]  2%|▏         | 6/250 [00:25<17:58,  4.42s/it]  3%|▎         | 7/250 [00:29<17:43,  4.38s/it]  3%|▎         | 8/250 [00:34<18:20,  4.55s/it]  4%|▎         | 9/250 [00:39<18:49,  4.69s/it]  4%|▍         | 10/250 [00:43<18:07,  4.53s/it]  4%|▍         | 11/250 [00:47<17:29,  4.39s/it]  5%|▍         | 12/250 [00:51<17:24,  4.39s/it]  5%|▌         | 13/250 [00:56<17:10,  4.35s/it]  6%|▌         | 14/250 [01:00<16:52,  4.29s/it]  6%|▌         | 14/250 [01:04<18:00,  4.58s/it]
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c56f75ae9952>", line 11, in <module>
    agent.learn()
  File "../src/agent.py", line 139, in learn
  File "../src/agent.py", line 48, in update_target_networks
    target_actor_weights[index] = tau * actor_weights[index] + (1 - tau) * target_actor_weights[index]
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2045, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'KeyboardInterrupt' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1170, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1503, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 1461, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 708, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/inspect.py", line 754, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 391, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 425, in _joinrealpath
    if not islink(newpath):
  File "/Users/anton/.conda/envs/reinforcement_learning/lib/python3.8/posixpath.py", line 167, in islink
    st = os.lstat(path)
KeyboardInterrupt
