2021-01-04 08:50:40,152 INFO    MainThread:2938967 [wandb_setup.py:_flush():70] setting env: {}
2021-01-04 08:50:40,152 INFO    MainThread:2938967 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-04 08:50:40,152 INFO    MainThread:2938967 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-04 08:50:40,152 INFO    MainThread:2938967 [wandb_init.py:_log_setup():303] Logging user logs to /home/anton/Projects/reinforcement_learning/ddqn/src/wandb/run-20210104_085040-1meq6f72/logs/debug.log
2021-01-04 08:50:40,152 INFO    MainThread:2938967 [wandb_init.py:_log_setup():304] Logging internal logs to /home/anton/Projects/reinforcement_learning/ddqn/src/wandb/run-20210104_085040-1meq6f72/logs/debug-internal.log
2021-01-04 08:50:41,522 INFO    MainThread:2938967 [wandb_run.py:_console_start():1237] atexit reg
2021-01-04 08:50:41,523 INFO    MainThread:2938967 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2021-01-04 08:50:41,525 INFO    MainThread:2938967 [wandb_run.py:_redirect():1107] Redirecting console.
2021-01-04 08:50:41,525 INFO    MainThread:2938967 [redirect.py:install():204] install start
2021-01-04 08:50:41,525 INFO    MainThread:2938967 [redirect.py:install():219] install stop
2021-01-04 08:50:41,525 INFO    MainThread:2938967 [redirect.py:install():204] install start
2021-01-04 08:50:41,525 INFO    MainThread:2938967 [redirect.py:install():219] install stop
2021-01-04 08:50:41,526 INFO    MainThread:2938967 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-04 08:55:46,912 INFO    MainThread:2938967 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-04 08:55:46,912 INFO    MainThread:2938967 [wandb_run.py:_restore():1179] restore
2021-01-04 08:55:46,912 INFO    MainThread:2938967 [redirect.py:uninstall():223] uninstall start
2021-01-04 08:55:46,913 INFO    MainThread:2938967 [redirect.py:_stop():278] _stop: stdout
2021-01-04 08:55:46,913 INFO    stdout    :2938967 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2021-01-04 08:55:46,913 INFO    MainThread:2938967 [redirect.py:_stop():284] _stop closed: stdout
2021-01-04 08:55:46,913 INFO    stdout    :2938967 [redirect.py:_pipe_relay():136] relay done done: stdout
2021-01-04 08:55:46,914 INFO    MainThread:2938967 [redirect.py:_stop():290] _stop joined: stdout
2021-01-04 08:55:46,914 INFO    MainThread:2938967 [redirect.py:_stop():292] _stop rd closed: stdout
2021-01-04 08:55:46,914 INFO    MainThread:2938967 [redirect.py:uninstall():227] uninstall done
2021-01-04 08:55:46,914 INFO    MainThread:2938967 [redirect.py:uninstall():223] uninstall start
2021-01-04 08:55:46,914 INFO    MainThread:2938967 [redirect.py:_stop():278] _stop: stderr
2021-01-04 08:55:46,914 INFO    MainThread:2938967 [redirect.py:_stop():284] _stop closed: stderr
2021-01-04 08:55:46,915 INFO    stderr    :2938967 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2021-01-04 08:55:46,915 INFO    stderr    :2938967 [redirect.py:_pipe_relay():136] relay done done: stderr
2021-01-04 08:55:46,915 INFO    MainThread:2938967 [redirect.py:_stop():290] _stop joined: stderr
2021-01-04 08:55:46,915 INFO    MainThread:2938967 [redirect.py:_stop():292] _stop rd closed: stderr
2021-01-04 08:55:46,915 INFO    MainThread:2938967 [redirect.py:uninstall():227] uninstall done
2021-01-04 08:55:46,918 INFO    MainThread:2938967 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "37e5674a4a9344a9ae24f3e10957ecec"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 731
      total_bytes: 731
    }
  }
}

2021-01-04 08:55:48,924 INFO    MainThread:2938967 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "d6a4b1e5742d4d539c1f826a2878d4e8"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 10103
      total_bytes: 10103
    }
  }
}

2021-01-04 08:55:50,060 INFO    MainThread:2938967 [wandb_run.py:_show_files():1536] logging synced files
2021-01-04 08:55:50,063 INFO    MainThread:2938967 [internal.py:handle_exit():138] Internal process exited
